Algoritmo sin_titulo
	Definir matriz, genz Como Caracter
	Definir size Como Entero
	Definir bandera Como Logico
	
	Gen(genz, size, bandera)
	
	Dimension matriz(size, size)
	

	si bandera = Verdadero Entonces
		rellenarMatriz(genz, size, matriz)
		mostrarMatriz(genz, size, matriz)
		verificacionGenZ(size, matriz)
	SiNo
		Escribir "Error de dimension."
		Escribir "Dimesion [", size, ",", size, "]"
		
	FinSi
	
FinAlgoritmo

SubProceso Gen (genz Por Referencia, size Por Referencia, bandera Por Referencia)
	
	//genz = "ACDDCADBCDABDBBA"
	//	genz = "CACBCACAC"
	//genz = "CCADDBACCDDDDBDBCCABBAABDBCDCADDABABCDCDDABBBCABBABBDCADCCDABDDACDBBBDBDCCDDCABCAAAACDCDCCACDCDDADAADDACBDBCCDDBCBCBBAAADDAADCAABBBCBCCBCBDBCCBBCBABADAACDBDBADCBBACDADAADABBDBDBDBDCCDDCABCCCCCADBBBBCCDACCBBBDBDAADDBCCBCCBCBDDDDCCBAAACDDBBCAABAADABBBCCCCDCCBBDCDABCDACBCBACDBCCDABDBDCDCADCCBBADDBDCCADCCDCCACCDCDBCDBBADBAADBBCAADDABCAADADAABAACCBABDADADADDBCABDCCBBAADDDCDDCBADBCACCAAADCCDDABDBACBCAAADDBADBDACDDBDCBDCCCDDCACBCCCACCCCBACBAAAAACBCBCDAADCAACBCABDDABCBCBACCADABBBABBBBBAACADDDDBABACADAAABDDDCCDCACAACACADADBABACBABDBBADCDBBDACDCAABCADDBDBDCAABDCDABDDADDCDDBCBCDADCDBBDACABCDAABBCBADDDBCBADCABACDCABBCBCBCBCADBABBDBCCCADCADDCBABBDDDBBCBCDABACDDDABCCDBACCBDBADADDDAAACBDCDCCAACBDDCDCBADACDDDDBDCBAACDADBBDBDBCCACADBAABBAADAADDDACDDCDBDDBBDAADDAACCCACDBBBBBDCDCDDDABBCBAAADACADDCDCDCBCDCACAAABCADBDBBDDACCBBDABDDBCADCCCADDCDBACBBBDAADDCDAAADBBCDADBDBCBDDCAABCCDCCDCABCAACADADAACADDBBDABAABACDACDCDBBDDCCBCBCAAACBDBDBBBDBDBBCADCBACDCCBDACBBACBCADCDBACCADCDBDCDBBACBBCDCAAAAABCCDDCDDBBCBABCBCAABDBCCACBABDCABAACBDBDBCCCCADBBCDCCCAABADBACDDBADCDCAADDDCBDDBDCDCCCCCCCDBCDDBACBBCDACDADCACBDBBCCCDCCBCBCDACBDDDACCCAADBDBBDADDCCDDDBCDABCCBACCCCCBAACCBCABAAABBCABBCACCCABCDACBCDBDACACDDCACBCBBCCADABCBBDDABADDAAABACCBDCDABCBBBBACCDABAACDCACCCBBCDDACCDBCBCBAACBBBBADBCBCDABAAAABADAAAACDACADACDBBCCABADDDCACDCAACCDABBDBDAABADDBDCCCACDADBDDDCBBCBDCADCBCDAABDDDDBBBBCDDCC"
	//genz = "ABAABBCBD"
	//genz = "ADDDABBDD"
	//	genz = "BCAADCCBABCCBABB"
	//	genz = "CDDACCACCACAAABC"
	//genz = "BCBBABBACBBBBCBB"
	genz = "ACCDBBADDDCCBACABDCBDCBADBDACBBBBDAABBCCBAACCABDBDCDDABDBDADAAACBBBBCDDDCBBBDDCDABBDDABDBDBBACADCDAAADACDDDACCDCACDDABACDCCCAABDDCCACDADDBCBAACCDBCBCDDDCAACCBAADCBBBCDCBBACBDCCDDADBABCAABBACABDCAACCBDADDCAAACCDBDBBCDDDDDACBCDDADDDDCBADADBDCADDABBCDAACBCCDDDADDADADAACCACDCDDABCCCADABBACDACCAADDBCBCCDADBCCADAAABDDDAABBABCADDCCAADDCDDCDCACBADADACADDAADCBDBCDBDDACDCBCDCCABBDCBACDDACCCDADBCADCACAAABBBCADDDDBCBACDBDAAADDDACCDACBBBADACCCDCACCBACDADBCBBDADACABAACBCCADDCCCCACCCCADBCCDAADCAABBABAADDBDADDABABCCABBCDDACCADAAADBBCCDBADCADCBBDADACCDDBCAAABBBDCAAAACBAADBABBABACDDBBCBDCDCADABABBDADCBADAACDBCBDABADBCBADCACADAABCDDCABACDDBDCBCBDCAAACBDABBCACBACCCBACACDCADBDCDCDDCAACDBDCBACDBBDAABDBBCBAAADBABDBAACAAACDCDAAABABDDDBCACADCBBAADCCDABCCCBBCACCBAABDAADDDCDACDDDBCDCCBABDABACCDCDCDABAABCABBADADCBDDACDDCDDCDACDADADCACBCDABABDDCCDBCCDABACDBDAABDBDDDBADDBACABDCDDBACDDBBDDBBACBCCAACABBDADDBCAACCBCCDADDBCAADDADCCCBAAABABBBBBCABAACADBCBBABACCABCDAABADCCCCDCCADDDCCABBDDDAAADDADACBBBCBDAADACABABBAACCCADADDABDBCADDDCCDBBCCBCDCDBDDDDCACDACDBBBDDBADDACADDADDABCACDCBBADDABBBDCBBDCDAABADDDDDBCACCCCAAACBCBCDBACCCDACCCDBCBDCBADBCDDACCDBDBDBCAAACDDCBAABDBCAADCADDBABABDCBCBCBBBCACBCADDCAAAAAACBBACBBCCACBDCDDDDADCAAACBABDDBDADBAADCBABDDBCDBABDBAADDDBACBBBCCCDBDDBDDAADBBADADDDCBCACBABCDBBABAADABCABCDBACBBBCDBADADDBDCBDABBDDDCDDCCACDCBDCADABAABCDCAACCDDBADBDBCDACAAACBCADCCCBAC"
	size = raiz(longitud(genz))

	si size = 3 o size = 4 o size = 37 Entonces
		bandera = verdadero
	sino 
		bandera = falso
	FinSi
FinSubProceso

SubProceso rellenarMatriz(genz Por Valor, size Por Valor, matriz Por Referencia)
	Definir i, j, aux, cont Como Entero
	
	aux = 0
	cont = 0
	
	para i = 0 Hasta size - 1 Hacer
		
		para j = 0 Hasta size - 1 Hacer
			
			matriz[i,j] = Subcadena(genz, j + aux, j + aux)
			cont = cont + 1
			
			si j = size - 1 Entonces
				
				aux = cont
				
			FinSi
			
		FinPara
		
	FinPara
	
FinSubProceso

SubProceso mostrarMatriz(genz Por Valor, size Por Valor, matriz Por Referencia)
	Definir i, j Como Entero
	
	para i = 0 Hasta size - 1 Hacer
		
		para j = 0 Hasta size - 1 Hacer
			
			Escribir Sin Saltar "|", matriz[i,j], "|"
			
		FinPara
		
		Escribir ""
		
	FinPara
	
FinSubProceso

SubAlgoritmo verificacionGenZ(size Por Valor, matriz Por Referencia)
	Definir i, j, cont1, cont2 Como Entero
	Definir ref1, ref2 Como Caracter
	
	cont1 = 0
	cont2 = 0
	ref1 = matriz[0,0]
	ref2 = matriz[0, size - 1]
	
	para i = 0 Hasta size - 1 Hacer
		
		para j = 0 Hasta size - 1 Hacer
			
			si matriz[i,j] = ref1 y i=j Entonces
				
				cont1 = cont1 + 1
				
			FinSi
			
		FinPara

	FinPara
	
	para i = 0 Hasta size - 1 Hacer
		
		para j = size - 1 Hasta 0 Hacer
			
			si i = (size - 1) - j Entonces
				
				si matriz[i,j] = ref2  Entonces
					
					cont2 = cont2 + 1
					
				FinSi
				
			FinSi
			
		FinPara
		
	FinPara
	
	Escribir ""
	
	si cont1 = size y cont2 = size Entonces
		
		Escribir "El gen ingresado es el Gen Z."

	SiNo
		
		Escribir "El gen ingresado NO es el Gen Z."

	FinSi
	
FinSubAlgoritmo

